/**
* AutoGenerated by @zuzjs/orm.
* @ Fri Dec 26 2025 14:29:37
*/
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from "@zuzjs/orm";


@Entity({ name: "push_tokens" })
export class PushTokens extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "int" })
	uid!: number;

	@Column({ type: "varchar", length: 255, default: "_" })
	hash!: string;

	@Column({ type: "varchar", length: 455, default: "_" })
	endpoint!: string;

	@Column({ type: "varchar", length: 455, default: "_" })
	p256dh!: string;

	@Column({ type: "varchar", length: 455, default: "_" })
	auth!: string;

	@Column({ type: "varchar", length: 30, default: "0" })
	stamp!: string;

	@Column({ type: "tinyint" })
	status!: number;

}