/**
* AutoGenerated by @zuzjs/orm.
* @ Fri Dec 26 2025 14:29:37
*/
import { Entity, BaseEntity, PrimaryColumn, Column } from "@zuzjs/orm";


@Entity({ name: "settings" })
export class Settings extends BaseEntity {

	@PrimaryColumn()
	okey!: string;

	@Column({ type: "varchar", length: 155, default: "__" })
	value!: string;

	@Column({ type: "varchar", length: 20, default: "0" })
	stamp!: string;

}