/**
* AutoGenerated by @zuzjs/orm.
* @ Mon Feb 16 2026 00:53:56
*/
import { Entity, BaseEntity, PrimaryColumn, Column } from "@zuzjs/orm";


@Entity({ name: "settings" })
export class Settings extends BaseEntity {

	@PrimaryColumn()
	okey!: string;

	@Column({ type: "varchar", length: 155, default: "__" })
	value!: string;

	@Column({ type: "varchar", length: 20, default: "0" })
	stamp!: string;

}