/**
* AutoGenerated by @zuzjs/orm.
* @ Fri Dec 26 2025 14:29:37
*/
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from "@zuzjs/orm";

export enum Isadmin { Yes = "yes", No = "no" }
export enum Status { Yes = "yes", No = "no" }

@Entity({ name: "users_sess" })
export class UsersSess extends BaseEntity {

	@PrimaryGeneratedColumn()
	ID!: number;

	@Column({ type: "int", default: 0 })
	uid!: number;

	@Column({ type: "varchar", length: 455, default: "none" })
	token!: string;

	@Column({ type: "varchar", length: 50, default: "0" })
	expiry!: string;

	@Column({ type: "varchar", length: 255, default: "none" })
	uinfo!: string;

	@Column({ type: "enum", enum: Isadmin, default: "no" })
	isadmin!: Isadmin;

	@Column({ type: "enum", enum: Status, default: "yes" })
	status!: Status;

}